imports:
    - { resource: "@SyliusProductBundlePlugin/config/resources/*.yaml" }
    - { resource: "@SyliusProductBundlePlugin/config/services.php" }
    - { resource: "@SyliusProductBundlePlugin/config/twig_hooks/**/*.yaml" }

framework:
    messenger:
        buses:
            sylius_product_bundle.command_bus: ~

sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            icon: "tabler:plus"
                            header:
                                label: sylius.ui.type
                            links:
                                simple:
                                    label: sylius.ui.simple_product
                                    route: sylius_admin_product_create_simple
                                configurable:
                                    label: sylius.ui.configurable_product
                                    route: sylius_admin_product_create
                                bundle:
                                    label: sylius_product_bundle.ui.bundle
                                    route: sylius_product_bundle_admin_product_create_bundle
